name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  api_client:
    path: ../
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  super_app_bridge:
    git:
      url: https://github.com/devnoaman/super_app_repo.git
      path: packages/super_app_bridge
  super_app_common:
    git:
      url: https://github.com/devnoaman/super_app_repo.git
      path: packages/super_app_common
      ref: e117fbd551ada7e9eb8776ae9cb56c6b3a53cab4
  super_app_manager:
    git:
      url: https://github.com/devnoaman/super_app_repo.git
      path: packages/super_app_manager
      ref: e117fbd551ada7e9eb8776ae9cb56c6b3a53cab4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
